# Generated by Django 4.2.2 on 2023-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
